### ISSUE TITLE
Encountered an error, saying "RuntimeWarning: divide by zero encountered in log   return -val_probs.dot(np.log(val_probs))"

### ISSUE THREAD

**Issue by uigoku** [jabbermonkey/dtree_bias_var#2]
I am attaching the photo of the terminal, please help.
![pythonerror](https://cloud.githubusercontent.com/assets/14887349/25130366/8a1abe76-245f-11e7-9b95-3157ca7a5613.png)

**Comment by paulc00** [comment]
Hmm, I just checked it and worked for me cloned into a new ubuntu install w/ the latest anaconda. What's your output for `pip freeze`?

**Comment by uigoku** [comment]
`appdirs==1.4.0
attrs==15.2.0
BeautifulSoup==3.2.1
beautifulsoup4==4.5.3
blinker==1.3
browsercookie==0.6.3
builtwith==1.3.2
chardet==2.3.0
configglue==1.1.2
configobj==5.0.6
cryptography==1.2.3
cssselect==1.0.1
cycler==0.9.0
debtags==2.0
decorator==4.0.6
defer==1.0.6
deluge==1.3.12
dirspec==13.10
duplicity==0.7.6
ecdsa==0.13
enum34==1.1.2
f.lux-indicator-applet==1.1.10rc0
feedparser==5.1.3
future==0.16.0
gyp==0.1
httplib2==0.9.1
idna==2.0
ipaddress==1.0.16
ipython==2.4.1
keyring==10.2
lockfile==0.12.2
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
matplotlib==1.5.1
mechanize==0.2.5
mpmath==0.19
mysql-connector-python==2.0.4
nemo-emblems==3.2.3
netifaces==0.10.4
numpy==1.12.0
oauthlib==1.0.3
oneconf==0.3.9
packaging==16.8
PAM==0.4.2
paramiko==1.16.0
parsel==1.1.0
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
protobuf==2.6.1
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
PyDispatcher==2.0.5
pygobject==3.20.0
pyinotify==0.9.6
PyJWT==1.3.0
pyodbc==3.0.7
pyOpenSSL==0.15.1
pyparsing==2.1.10
pyparted==3.10.7
pyserial==3.0.1
pysmbc==1.0.15.5
pysqlite==2.7.0
pytesseract==0.1.6
python-apt==1.1.0b1
python-dateutil==2.4.2
python-debian==0.1.27
python-libtorrent==1.0.7
python-whois==0.6.5
pytz==2014.10
pyxdg==0.25
queuelib==1.4.2
reportlab==3.3.0
scipy==0.17.0
scour==0.32
Scrapy==1.3.2
SecretStorage==2.3.1
selenium==3.0.2
service-identity==16.0.0
simplegeneric==0.8.1
six==1.10.0
SQLAlchemy==1.0.11
sympy==0.7.6.1
Twisted==16.0.0
uTidylib==0.2
vboxapi==1.0
virtualenv==15.1.0
w3lib==1.17.0
youtube-dl==2017.2.16
zope.interface==4.1.3
`
this is the output I get for `pip freeze`

**Comment by paulc00** [comment]
I see you're running python 2. This was developed in python 3. 

The specific failure you are seeing is as follows:
During division, if the dividend is an integer python 2 treats the operation as integer division but python 3 treats it as floating point division. In this case the `entropy()` function `numpy.unique()` returns a list of `int` values. Unless `attribute_data` is [0], [1] or [0, 1], val_probs will end up with a list of zeros for which the log will be undefined.

I was briefly tempted to try and backport the code but this error would be only the first of several, potentially tricky, issues under python 2. The majority of python programmers these days are writing new code in python 3 and the arguments for staying with python 2 have mostly disappeared over the past few years.

The fix for the entropy function is to specify the dtype in line 34 of dtree.py:
```python
    val_probs = np.array(val_freqs, dtype=np.float32) / len(attribute_data)
```
You should also add an
```python
from __future__ import print_function
```
to the beginning dtree_test.py so the `print()` function works for python 2

I'm sure there would be several other places where the integer dividend handling would be an issue but I don't believe the backport is worth the effort. I'd be happy to consider a pull request if you want to backport the program yourself but I'd suggest you just run the code in python3 instead.

I'll add some comments to the code and a note in the readme to make it clear that this is python 3 code.
