### ISSUE TITLE
log instead of log2 used in Entropy calculation

### ISSUE THREAD

**Issue by redborian** [jabbermonkey/dtree_bias_var#3]
at `dtree.py` line `37`

**Comment by paulc00** [comment]
Computer scientists often choose base 2 for entropy since it defines entropy in terms of bits but *any base is valid* as long as the same base is used in any comparisons. Note that log2 (base 2) entropy is simply log (base e) entropy multiplied by a constant, [log2(e)~=1.4427]. 

Claude Shannon describes the (freedom of) choice of logarithmic base on page 2 of [the paper where he first introduced the concept of entropy](https://github.com/paulc00/dtree_bias_var/files/2532563/bstj27-3-379.pdf).

I'm closing this issue but if you have some other justification and/or requirement for the change please feel free to open a new issue.
